name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"

jobs:
  compile-examples:
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports
      UNIVERSAL_LIBRARIES: |
        - source-path: ./

    strategy:
      matrix:
        board:
          - fqbn: arduino:megaavr:nona4809
            type: arduino_megaavr
          - fqbn: arduino:esp32:nano_nora
            type: arduino_esp32

        include:
          - board:
              type: arduino_megaavr
            platforms: |
              - name: arduino:megaavr
          - board:
              type: arduino_esp32
            platforms: |
              - name: arduino:esp32
            libraries: |
              - name: EspSoftwareSerial

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile sketches
        uses: arduino/compile-sketches@v1.1.0
        with:
          platforms: ${{ matrix.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            ${{ env.UNIVERSAL_LIBRARIES }}
            ${{ matrix.libraries }}

          sketch-paths: |
            - examples

          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SKETCHES_REPORTS_PATH }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
